### ISSUE TITLE
IJulia fails on 1.7 with Mac M1

### ISSUE THREAD

**Issue by ctkelley** [JuliaLang/IJulia.jl#1027]
Just installed 1.7 on M1 mac. Started from scratch with no .julia directory. 

Tried to fire up a notebook and got this
```
julia> notebook(;dir=pwd())
install Jupyter via Conda, y/n? [y]: y
[ Info: Downloading miniconda installer ...
ERROR: Unsupported miniconda platform: MacOSX-arm64
```

**Comment by ctkelley** [comment]
OK. I will file on Conda.jl

**Comment by lewisl** [comment]
Unfortunately, Anaconda has not gotten around to creating a Python build for Apple silicon.

Your only choices are to use the system Python, which is something like Python 3.8.x or to use the Python download from the Python software foundation. They have a specific build for Apple Silicon, which is 3.10.0.

I have done the latter. 

IJulia and Julia and the Visual Studio Code internal code for Jupyter Notebooks kinda/sorta works. Seems like Julia and notebooks get out of sync very often and very easily as the Visual Studio Code internal notebooks lose cell results all the time. 

I will give Jupyter Lab a try and report back.

**Comment by stevengj** [comment]
Conda.jl should work now on Apple Silicon, because it now defaults to Miniforge (see also https://github.com/JuliaPy/Conda.jl/issues/208).

**Comment by lewisl** [comment]
Conda.jl may certainly work, but Anaconda Python is only for Intel processors at this point. That will certainly run on Apple Silicon, but in emulation mode (which is not bad, but not as fast as native).

From: "Steven G. Johnson" ***@***.***>
Reply-To: "JuliaLang/IJulia.jl" ***@***.***>
Date: Friday, December 3, 2021 at 7:43 PM
To: "JuliaLang/IJulia.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Comment ***@***.***>
Subject: Re: [JuliaLang/IJulia.jl] IJulia fails on 1.7 with Mac M1 (Issue #1027)


Conda.jl should work now on Apple Silicon, because it now defaults to Miniforge (see also JuliaPy/Conda.jl#208<https://github.com/JuliaPy/Conda.jl/issues/208>).
