### ISSUE TITLE
Is html supported in the Ijulia port 

### ISSUE THREAD

**Issue by sononix** [JuliaLang/IJulia.jl#264]
This works fine in ipython 
<code>
%%html
[h1]Hello World[/h1]
</code>

but not in Ijulia where is generates 

<code>
LoadError: UndefVarError: html not defined
while loading In[1], in expression starting on line 1
</code>

are html tags supported in Ijulia

**Comment by Carreau** [comment]
`%%html` is an IPython-kernel specific syntax. `%%something` is an extra syntax on top of python we (IPython dev) use for convenience because we cannot extend python language. 

IIRC julia has not the need for "Magics" because they have macro, and custom string literals. (don't remember the name of that)

See this : https://github.com/JuliaLang/IJulia.jl/issues/12 for previous dicussion. 

Closing, someone will probably chime in to tell you what's the Julian way of doing it.

**Comment by stevengj** [comment]
`display("text/html", "<h1>Hello world</h1>")` ... see the [Julia manual on rich i/o](http://docs.julialang.org/en/latest/stdlib/io-network/#multimedia-i-o).
