### ISSUE TITLE
killing notebook is unreliable

### ISSUE THREAD

**Issue by YingzhouLi** [JuliaLang/IJulia.jl#270]
After I run notebook() in Julia and close the notebook, my Julia will be extremely slow.
I have no idea if this is caused by my improperly exiting notebook (I always use ctrl+c in the terminal to interrupt it).
The following error message pop-up when the notebook is interrupted:
ERROR: interrupt
 in process_events at ./stream.jl:537
 in wait at ./task.jl:273
 in wait at ./task.jl:194
 in stream_wait at ./stream.jl:263
 in wait at ./process.jl:619
 in success at process.jl:492
 in notebook at /home/ryanli/.julia/v0.3/IJulia/src/IJulia.jl:177
 in notebook at /home/ryanli/.julia/v0.3/IJulia/src/IJulia.jl:176

**Comment by stevengj** [comment]
I think the background event-processing tasks are still running...

**Comment by stevengj** [comment]
Right now, if you want to kill the notebook you should really just close Julia entirely; the `notebook()` command is not designed to be interruptable.  Possibly the problem here is due to the unreliability of ctrl-C in Julia when killing C code (see JuliaLang/julia#2622).

Maybe the right thing is for `notebook()` to fork a process and return a task object that can be stopped with `stop_notebook()`.

**Comment by vtjnash** [comment]
Perhaps you want to add a detach() to that Cmd object? I don't know how you are interrupting the code currently

**Comment by stevengj** [comment]
@vtjnash, people are just interrupting it with ctrl-c right now.

**Comment by vtjnash** [comment]
Oh. Yes, it should have a detach call then so that signals don't propagate to the child processes

**Comment by stevengj** [comment]
But if you run `detach`, then even closing Julia will not kill it, which will be confusing for users (who will soon have dozens of `ipython` processes running).  Is there an intermediate choice?

**Comment by vtjnash** [comment]
True. Currently Julia workers kill themselves when they see a SIGPIPE. Can IPython do something similar?

**Comment by stevengj** [comment]
I think IPython exits cleanly only on SIGINT or SIGTERM; see ipython/ipython#1609

**Comment by amitmurthy** [comment]
@vtjnash , we changed julia processes to ignore SIGPIPE. But they do exit when the socket connected to the master process is closed, actually on any error in the the task blocking on a read from the master.

**Comment by amitmurthy** [comment]
related - https://github.com/JuliaLang/julia/issues/9095

**Comment by stevengj** [comment]
This still seems to be a problem on MacOS due to JuliaLang/julia#18146 ... the `notebook()` command ends up killing the wrong process.

**Comment by stevengj** [comment]
Okay, the problem on my machine seems to be because (for historical reasons) my IJulia was running the notebook via `ipython notebook`.  When I reconfigured it to use `jupyter notebook`, the problem went away.   So, I'm going to close this as hopefully it is unlikely to affect people using a modern Jupyter version.

I still think that there should be a way to `kill` a whole process group, though.
