### ISSUE TITLE
valid code for tab completion of unicode characters

### ISSUE THREAD

**Issue by koaning** [JuliaLang/IJulia.jl#274]
This question is linked to [this stackoverflow question](http://stackoverflow.com/questions/28460248/why-can-i-not-use-the-unicode-characters-%E2%88%9A-and-%E2%88%80-in-assignments). 

Many tab completions work, but don't make valid code. Including `\bar` to draw a overline and `\forall` for the forall symbol. Perhaps it would be better to remove these.

[Here](https://github.com/JuliaLang/julia/blob/d234b4ff56df9ce85198dcdd8d9ef1073b2436fc/base/operators.jl#L403-L432) is a list of characters that Julia allows. Perhaps for now iJulia should refrain to these characters.

**Comment by jiahao** [comment]
Combining characters like `\bar` cannot be used to start a variable name.

```jl
julia> ̄ = 1
ERROR: syntax: invalid character "̄"

julia> x̄ = 1
1
```

I'm not sure why we disallow `∀`.

**Comment by Carreau** [comment]
Watch out, there is also a bug in current chrome that combine some combining character with next instead of previous: 

https://code.google.com/p/chromium/issues/detail?id=445028

This lead people to do `\bar``x` for `x̄` instead of `x``\bar`. 
Affect `\vect`IIRC, but not `\dot` ...

As for `√`, be careful there might be many. u221A most of the time, but some OS  use `⎷` (might look identical) which is u23B7, I'm not sure if there are other.

We could make completion smarter with that but I'm not sure it is worth.

**Comment by stevengj** [comment]
In any case, the list of tab completions comes from Julia, not IJulia, so that discussion should take place in a Julia issue, not here.

(Putting aside invalid usages of combining characters as mentioned above, it is true that we currently complete some LaTeX symbols like `\forall` that aren't valid Julia identifiers or operators.  In the case of `\forall`, this is because we are still deciding whether `∀` should be an identifier or an operator, I think.)
