### ISSUE TITLE
Trying to install IJulia system-wide

### ISSUE THREAD

**Issue by swt30** [JuliaLang/IJulia.jl#279]
I've managed to convince a bunch of people in the department to try Julia. Great! We have a system-wide installation and use environment modules to make Julia available to everyone, and most things are working really nicely so far. Next step is to put packages on the cluster to save users having to install them to their home directories. IJulia is one of these. 

I thought the notebook would be a great way to run an introductory tutorial, but we've been struggling to get it working with `ipython notebook --profile julia`. I think it's because the system-wide build step for IJulia puts some linking information in `~/.ipython/profile_julia`. So when a user starts up IJulia this folder isn't there yet. No information as to where the system-wide IJulia installation is means it just opens a normal IPython session. Users can `Pkg.add("IJulia")` individually to get it to work, but that defeats the purpose of having a system-wide copy. 

I'm investigating the role of the `profile_julia` folder to see what goes into it. In the meantime, any ideas? Would linking `~/.ipython/profile_julia` to the system-wide folder, or copying the system-wide folder across, work? Or is there some alternate version of the build command I could use to tell IJulia to re-write its location into a given user's `.ipython/profile_julia` folder?

**Comment by swt30** [comment]
Re-running the build step after setting `JULIA_PKGDIR` to the system package location worked for me.

```console
> export $JULIA_PKGDIR=/path/to/system/julia/packages/v0.x/
> julia $JULIA_PKGDIR/IJulia/deps/build.jl
```

You'd need to do this for each user after installing IJulia system-wide. Is it worth adding a function to IJulia to perform this step of re-running the build script for an arbitrary Julia/IJulia location, for the case where a user can't run Pkg.build?

**Comment by stevengj** [comment]
@swt30, look at the Julia `LOAD_PATH` variable: that is where you should install system-wide packages (e.g. `/usr/local/share/julia/site/v0.3/` ... you probably want `/usr/local` for software not controlled by the OS package manager).

Then you can set the `IPYTHON_DIR` environment variable in order to create a system-wide IPython directory.   e.g. `IPYTHON_DIR=/usr/local/share/ipython`.   Then the `Pkg.build("IJulia")` will install the Julia profile to this directory, and users can run `ipython notebook --profile julia` and it will work (assuming that their `IPYTHON_DIR` is set)

**Comment by swt30** [comment]
I didn't know about `IPYTHON_DIR`. Thanks! I'll give that a try. We use environment modules to load in Julia for each user, so it should be easy to change the Julia module to do this. I guess the only issue would be if it stops people customising their ipython installation, but I've never had cause to do that before, so for people just wanting to try the language it should be fine.

**Comment by stevengj** [comment]
Great, feel free to re-open this if that doesn't work for you.

**Comment by Carreau** [comment]
Quick read through, I woudl suggest having a look at https://github.com/jupyter/jupyterhub and ipython 3.0 (which is now in RC, release next week probably). It is much more friendly to multiuser (that's the goal of JupyterHub), and there are a bit more logic for systemwide vs per user configuration.

**Comment by swt30** [comment]
Awesome - been looking forward to seeing what ipython 3 / jupyter can do.

**Comment by Carreau** [comment]
> Awesome - been looking forward to seeing what ipython 3 / jupyter can do.

It should be 99% ready, so feel free to try and ask if you have issues !

**Comment by swt30** [comment]
Unfortunately IJulia is still not working with this shared `IPYTHON_DIR` approach, but that's due to an issue with the way Nettle finds itself---it uses `Pkg.dir("Nettle")`, which returns the user's `.julia` directory instead of the system directory. I commented about this here: https://github.com/JuliaLang/julia/issues/8679#issuecomment-75753355

**Comment by yuyichao** [comment]
In case anyone has trouble installing `IJulia.jl` systemwise, [here](https://github.com/yuyichao/arch-pkg/blob/master/pkg/all/ijulia-git/PKGBUILD)'s my packaging script to do that. With `julia-0.4-dev` and `ipython-3.0` (and I'm pretty sure these are not the lowest requirement). The user doesn't have to do anything special or setting any environment variables to get it working.

It only requires a small patch on `IJulia.jl` in order to set the correct system path.

**Comment by stevengj** [comment]
What was the patch?

**Comment by yuyichao** [comment]
@stevengj You can find the patch either [in the repo for the packaging script](https://github.com/yuyichao/arch-pkg/blob/master/pkg/all/ijulia-git/0001-support-system-wise-install-ijulia.patch) and it is also the same patch I submitted as a pull request a while ago. https://github.com/JuliaLang/IJulia.jl/pull/296.

The issue is that when compiling the package before installing, there's no way for the build system itself to figure out what is the path it is going to be installed to (unless it is passed in as an option).

**Comment by stevengj** [comment]
Okay, merged.
