### ISSUE TITLE
Input Output error after stopping Notebook 

### ISSUE THREAD

**Issue by smukoehler** [JuliaLang/IJulia.jl#283]
After I close all my IJulia notebook tabs and return to Julia in my terminal (on Mac OS 10.10) by using Control-C, there seems to be an issue with keyboard input. For some reason, only about half the keys I type make it to the Julia command line. Upon exiting Julia, I get the following error:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/skoehler/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/skoehler/anaconda/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/skoehler/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 733, in _confirm_exit
    line = sys.stdin.readline()
IOError: [Errno 5] Input/output error
```

Any idea what's going on? Is there a better way to stop the Notebook server? Thanks!

**Comment by stevengj** [comment]
Right now, if you want to kill the notebook you should really just close Julia entirely; the `notebook()` command is not designed to be interruptable.

Possibly the problem here is due to the unreliability of ctrl-C in Julia when killing C code (see JuliaLang/julia#2622).   Maybe the right thing is for `notebook()` to fork a process and return a task object that can be stopped with `stop_notebook()`.

**Comment by stevengj** [comment]
Closing this in favor of #283.
