### ISSUE TITLE
multi-user Julia notebook

### ISSUE THREAD

**Issue by berceanu** [JuliaLang/IJulia.jl#316]
I would like to set up multi-user notebooks on my server for my collaborators and I to do interactive computing in Julia. 
I am not sure weather the way to go is via https://github.com/jupyter/jupyterhub or https://github.com/JuliaLang/JuliaBox, but I think both there projects are connected with IJulia so that is why I post here. 
What is the way to go and how achievable is my goal at the present time?

**Comment by Carreau** [comment]
Follow the instruction of installing Jupyter-hub. Then you will have multi-user server. 
After that, either install globaly julia/IJulia, to have a julia kernel availlable for each users, or let each user do it. 

Julia and JupyterHub have roughly the same goals, JuliaBox predate JupyterHub, but Jupyterhub is less tightly coupled with rest of Jupyter/IPython.

**Comment by berceanu** [comment]
Less tightly in what sense? I thought if anything, it would be more coupled, as it is an initiative of the original ipython people isn't it?
So can two users simultaneously edit the same notebook? I am thinking of something along the lines of Google Docs.

**Comment by Carreau** [comment]
Less tightly in the sens that JupyterHub cold perfectly function for something else than the IPython notebook. It Basically act as a Proxy/Login page to redirect people to their server. We can enter into more detail if you wish.  

And the IPython people are trying to do each of their pieces without coupling, because people like you might want to not use IPython at all and only Julia :-) Also we are splitting IPythonin a dozen or so components that can work together, but are reusable. 

I [am working](https://github.com/jupyter/jupyter-drive)  on Google drive real time integration. Which is not ready yet, and require a few deep refactoring in the notebook architecture to be do The Right Way, in the sens that it's pluggable so that you can use a local firebase or any other RT framework.

If you want realtime collaboration now you can give a try to [sagemathcloud](http://www.sagemathcloud.org/)

In both cases IJulia is not really related to any of theses project. It is "Just" a think  layer that expose the Julia repl with the correct ZMQ network protocol.

Does that make sens ?

**Comment by berceanu** [comment]
Yes, thank you for the detailed response. Real time collaboration would be a very nice feature for non-git people :) Is sage math installable on my own server? By the way, they do not mention Julia support.

**Comment by Carreau** [comment]
Working on RT, would still be useful to have more people on Deck for that. 
I think that most of sagemath cloud be install locally. Though I'm not sure. Yes there should be Julia support as it uses IPython protocol for Python, so it should be a matter of just installing IJulia.

**Comment by stevengj** [comment]
Closing as not really an IJulia issue per se.
