### ISSUE TITLE
Problem Installing IJulia on Windows 7

### ISSUE THREAD

**Issue by DimitriKolnikov** [JuliaLang/IJulia.jl#369]
Hi,
My problem seems close to Issue #363,  however the patch does not seem to work for me.

When trying to build IJulia, I get the following message:

julia> Pkg.build("IJulia")
INFO: Building WinRPM
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/repomd.xml
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 3.2.0: ipython
============================================================================[ ERROR: IJulia ]====================================================================
invalid ASCII sequence
while loading c:\Users\Dimitri Kolnikov\.julia\v0.3\IJulia\deps\build.jl, in expression starting on line 64

===============================================================================
and the line 64 in the build file is:

append!(kernelcmd_array, ["-F", joinpath(ijulia_dir,"src","kernel.jl"), "{connection_file}"])

It seems a bit obscure to me...
If somebody could help ...
Thanks in advance ...

**Comment by greenflash1357** [comment]
I wanted to open the same issue.
I'm using Windows 10, Julia 3.11, Python 2.7, IPython 3.2 and IJulia 1.1.4.

I think the error is due to non ASCII characters in your IJulia directory (home directory). Maybe your user name contains special characters?

I could build Julia after manually writing the kernelcmd_array. But I think this could be done automatically. 

Unfortunately `joinpath()` returns an ASCIIString (line 62 in build.jl) if possible. Using an UTF8String solved the issue for me. But there is no implicit conversion, when calling `append!()` in line 64.

**Comment by stevengj** [comment]
Thanks for the bug report.  It should be fixed now — try `Pkg.checkout("IJulia"); Pkg.build("IJulia")` to get the latest version.

The problem was that `kernelcmd_array` was initialized to an array of a few strings, and then a few more strings were appended.  If the first few strings were ASCII, then it was initialized to an array of `ASCIIString`, and the error you saw was thrown if the appended strings were non-ASCII.  The solution was to explicitly declare a Unicode string type when initializing the array.

**Comment by greenflash1357** [comment]
The fix works for me.
Thanks.

**Comment by DimitriKolnikov** [comment]
It works for me too.
Thanks a lot for your reactivity !
