### ISSUE TITLE
IJulia console doesn't make plots

### ISSUE THREAD

**Issue by LordZorgoth** [JuliaLang/IJulia.jl#399]
If you run "ipython3 console --kernel=julia-0.[4 or 5]" and attempt 

using PyPlot
plot(1:5,1:5)

it returns a PyObject but doesn't make a plot on the screen.

Plots work fine in the notebook or with the plain julia command.

You can also make a plot using python in "ipython3 console" with a python kernel.

**Comment by stevengj** [comment]
This is arguably a PyPlot issue, not IJulia.

You can make plots in PyPlot with IJulia console by running `pygui(true)`.  It works in Python because IPython does not default to inline plots (you need to explicitly type `%matplotlib inline`, whereas PyPlot does.

I don't think there's much more we can do than say to write `pygui(true)`, however, since:

* The way the Jupyter architecture works, I don't think there is any way of telling what front-end is connected to the kernel.   So PyPlot has no way of distinguishing between the Jupyter notebook and console.

* As a practical matter, the console interface isn't really useful, since if you want a console you should just run `julia` and get the native REPL, which is much better.

**Comment by LordZorgoth** [comment]
I am somewhat confused because I thought I had tried pygui(true) last night, but it did in fact work.

The reason that I am using the console is because I am trying to run julia within ansi-term in emacs. The current inferior shell in emacs leaves a lot to be desired, and the ordinary julia program in ansi-term is extremely buggy, whereas the IJulia console is not.
