### ISSUE TITLE
is it possible to fix the version of ipywidgets Pkg.add("IJulia") installs?

### ISSUE THREAD

**Issue by shashi** [JuliaLang/IJulia.jl#451]
It would be nice if there is a version of IJulia.jl that is the last to pull ipywidgets 4.x, so that Interact's fixes to 0.3.x minor release can upper limit to that IJulia version, and a new 0.4.x release can depend on newer IJulia versions.

Can the version of Jupyter or at least ipywidgets IJulia pulls be fixed? This will help bug fixes be more resilient. The down side is a new release of Jupyter would need a new release of IJulia - which I think is a fair bargain.

**Comment by stevengj** [comment]
Since we don't install Jupyter ourselves (unless we are using the Conda Jupyter), all we can do is to have `Pkg.build` fail with an error if an unsupported version of Jupyter is found.

In any case, I don't know how this helps Interact — because it doesn't depend on IJulia, it can't specify a particular version of IJulia that it depends on.

Why can't Interact switch between two different versions of its code at runtime depending on what version of Jupyter IJulia was built with?

**Comment by stevengj** [comment]
Closing as the ipywidgets version conflicts seem to be a thing of the past.
