### ISSUE TITLE
Suggestion for  the IJulia Installation guide - especially for Mac users

### ISSUE THREAD

**Issue by OldGuyInTheClub** [JuliaLang/IJulia.jl#548]
After several hours of trying, I was able to get a Julia 0.5 kernel to talk to my macOs Sierra Jupyter Notebook (via Anaconda & Python 2.7).  Pkg.add("IJulia") kept failing but the error messages went by so fast, it took a long time and a lot of searching to debug.  

I suggest the following additions for https://github.com/JuliaLang/IJulia.jl for Mac users.   

1) Install Xcode for the git tools required in the installation process
2) ZMX on the Mac requires Brew: http://zeromq.org/intro:get-the-software followed by brew install zmq _before_ running the Pkg.add("IJulia")

**Comment by stevengj** [comment]
Neither Xcode nor Brew should be required, because all the dependencies should have precompiled binaries for Mac.

e.g. ZMQ uses [Homebrew.jl](https://github.com/JuliaPackaging/Homebrew.jl) to set up its own homebrew installation inside the `.julia` directory, so you should *not* need to install Brew. 

If any of the IJulia dependencies failed to install without Xcode or Brew, that is a bug and should be reported (with the exact error message and the output of `versioninfo(true)` at the appropriate package).
