### ISSUE TITLE
pkg add ijulia error

### ISSUE THREAD

**Issue by shankyjain** [JuliaLang/IJulia.jl#579]
Hi,
    I'm trying to add package ijulia after installing Julia. i'm doing this behind corporate proxy. when i run i get error
 
condaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>

An HTTP error occured when trying t oretrieve this URL.
HTTPS erros are often ntermittent, and a simple retry will get you on your way.

SSLError<SSLError<SSLError<"bad handshake: Error<['SSL routines', 'ssl3_get_server_certificatr'. 'certificate verify failed')],)",),),)

 any help on how i can fix this

**Comment by stevengj** [comment]
Since this is a problem that occurs when installing Conda, it should probably be reported at [Conda.jl](https://github.com/JuliaPy/Conda.jl), not in IJulia.

One thing to try would be to replace the `download(x, y)` calls in [Conda.jl](https://github.com/JuliaPy/Conda.jl/blob/master/src/Conda.jl) with `run(BinDeps.download_cmd(x, y))`, since I think the BinDeps downloader might be more robust.

Another option is to install Anaconda Python yourself and configure IJulia to use it by setting `ENV["JUPYTER"]` as explained in the [README](https://github.com/JuliaLang/IJulia.jl/blob/master/README.md).

**Comment by shankyjain** [comment]
Thanks, i did as suggested and it worked. I was trying to set proxy env variables as suggested in [https://github.com/JuliaLang/julia/issues/20948#issuecomment-287305414](url)  which i couldn't get to work anyhow.

**Comment by stevengj** [comment]
Which suggestion did you follow?

**Comment by shankyjain** [comment]
I had only tried with proxyhost:port. I saw ENV["HTTPS_PROXY"] was already set and i copied the same setting into ENV["HTTP_PROXY"]. I didn't try adding user:pass as i saw HTTPS_PROXY was by default populated without it.

```Julia
ENV["HTTP_PROXY"] = "http://user:pass@proxyhost:port"
ENV["HTTPS_PROXY"] = "http://user:pass@proxyhost:port"
```

**Comment by shankyjain** [comment]
sorry i think i misunderstood your question :)
I followed the Jupyter ENV variable setting as i had Anaconda already installed. I was hesitant earlier, as i read in some suggestion (although don't remember where) it's better to let ijulia have it's private jupyter to avoid some issues. Sorry for sounding vague.
