### ISSUE TITLE
access attachments

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/IJulia.jl#625]
Jupyter notebook cells now support attachments via drag and drop. It would neat if there was a way to access this data from within Julia (e.g. so that I could embed the data into the notebook).

**Comment by stevengj** [comment]
Yes, I was excited to see jupyter/notebook#621, though the lack of nbconvert support (jupyter/nbconvert#699) makes this of limited utility so far.

I don't think there is anything in the [jupyter protocol](http://jupyter-client.readthedocs.io/en/stable/messaging.html) that allows kernels to request attachment data, however.  You'd have to file a Jupyter issue about this.

Of course, if you have access to the filesystem you could use JSON.jl to parse the notebook data directly, I guess, but even that is a problem because of jupyter/notebook#1000, which means it is hard to find out the name of the current notebook.
