### ISSUE TITLE
DataFrames.jl show in IJulia

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/IJulia.jl#835]
When I add the following method definition to DataFrames.jl:
```
Base.show(io::IO, mime::MIME, df::AbstractDataFrame) = throw(ArgumentError("Unsupported MIME type $mime"))
```
IJulia stops rendering a `DataFrame` using `"text/html"` MIME type. In general this method should have no impact on display as it is more general than other methods defined in DataFrames.jl for display so it should never be called.

Here is a screenshot of a MWE:

![image](https://user-images.githubusercontent.com/6187170/56246652-db328380-60a2-11e9-901b-cf7b51a862e7.png)

**Comment by stevengj** [comment]
I think the issue is that the default definition of `showable` checks whether a method is applicable. By defining a generic ::MIME method you are therefore making showable return true for all MIME types, and IJulia is getting confused about what types you actually support. 

If you must define a show method for ::MIME, then you’ll need to define your own showable method(s) too, to return false for all mime types other than the ones you actually support. 

But as I recall, your show method basically did manual dispatch, and I really think you’d be better off defining individual show methods for each MIME type you support.

**Comment by bkamins** [comment]
Thank you for the explanation.

This general method was only needed because @nalimilan suggested to have a separate "no-op" method to which we can attach a docstring to.
