### ISSUE TITLE
[feature request] syntax highlight in vscode

### ISSUE THREAD

**Issue by johnnychen94** [JuliaLang/IJulia.jl#933]
I'm not sure if this is the right place to ask and I'm not sure if this is doable.

The `python` extension in vscode supports `.ipynb` files with a local jupyter server, and it's great to see that it works for the julia kernel, except that there's no meaningful syntax highlighting.

![image](https://user-images.githubusercontent.com/8684355/85360464-ccb7e580-b54b-11ea-93e0-155e55f3ad9d.png)

cc: @davidanthoff as it might be related to julia-vscode.

**Comment by davidanthoff** [comment]
No, this has nothing to do with julia-vscode. The Python VS Code extension is using a really unfortunate design for their Jupyter notebook support in general, although this problem is probably independent of that.

We are working on a native notebook support in julia-vscode that will have all the editor features from the extension, but right now it is a very early PR.

**Comment by Luis-gd** [comment]
That happens too with sagemath, it can run the cells but cannot highlight it

**Comment by stevengj** [comment]
IJulia has no influence on syntax highlighting — that is all done by other software (e.g. codemirror in Jupyter).

**Comment by davidanthoff** [comment]
We now know what we need to do to make all of this work, and all of the work has to happen on the Julia VS Code extension side (or rather we have to move some stuff from our extension into VS Code base). We're on it.
