### ISSUE TITLE
IJulia is very slow at first calculation

### ISSUE THREAD

**Issue by Alalalalaki** [JuliaLang/IJulia.jl#995]
I am new to Julia. I find that the first simple calculation always takes over 1 second and somehow `@time` does not count that time. This does not happen in the REPL.

![image](https://user-images.githubusercontent.com/31154974/110840262-dce54000-82e7-11eb-8124-d1eaf6c45c0e.png)

**Comment by travigd** [comment]
I think this happens because the first time you execute code, Julia is just-in-time compiling a bunch of IJulia-internal code (e.g., the code that communicates with Jupyter and formats the outputs of your code).

This doesn't show up when using `@time` since that compilation time happens outside of when your code is running (_i.e._, IJulia has to compile, **then** your `@time` code starts, **then** IJulia has to compile a bit more to display your result).

**Comment by Alalalalaki** [comment]
@travigd So basically this is an inevitable feature of IJulia and Julia?

**Comment by travigd** [comment]
For now. The community is constantly working on reducing compilation latency, but for now it's avoidable.

Typically, the recommendation is just to avoid starting and stopping lots of Julia process. If possible, prefer to use one long-lived Julia process since you only have to pay the compilation cost once.

**Comment by Alalalalaki** [comment]
Thank you very much for your advise.
